language: node_js
sudo: false
services:
  - mongodb
node_js:
  - "5.4"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
      - mongodb-3.0-precise
    packages:
      - clang-3.6
      - g++-4.8
      - mongodb-org-server