environment:
  matrix:
  # not yet supported for appveyor
  #- nodejs_version: "5.4"
  - nodejs_version: "5.3"
  - nodejs_version: "5.2"
  - nodejs_version: "5.1"
  - nodejs_version: "5.0"
  - nodejs_version: "4.2"

services:
  - mongodb

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off